### PR TITLE
Updating json files

### PR DESCRIPTION
**Pull request by Rakesh-97**
Add code for "Find Duplicacy" in any given root path.

### CODE REVIEW

**Comment by srbcheema1** [comment]
nice work @Spider34 
I am writing a short review on how git projects work.
just add temporary files like `cache files` to .gitignore they are useless for other users.
Also create a new branch while adding some feature, otherwise you will only be able to work on one feature at a time.

**Comment by vishichoudhary** [comment]
I have never seen pr worse than this. No description provided. Commit message are not clear.
 you may take help from https://medium.com/@meakaakka/a-beginners-guide-to-writing-a-kickass-readme-7ac01da88ab3

**Comment by vishichoudhary** [comment]
I am reporting your account for the same. People like should we ban from github.

**Comment by Souravirus** [comment]
Yeah I think @vishichoudhary is right. You should write more proper information in the commits and also please provide some description in the PR. 
Regards
Sourav

**Comment by srbcheema1** [comment]
hi @vishichoudhary @souravsahoo
thanks for the feedback.
@spider34 is our new developer, joined few days ago.
He is not much comfortable with git and github right now. But i could see that he is a quick learner and will learn easily. instead of discouraging him i would say you could encourage him for his hardwork and passion.

if there is any other issue or querry regarding work of my developer you may contact me directly on our mailing list or just ping me on my mail srbcheema1@gmail.com

**Comment by Souravirus** [comment]
Umm. What's your mailing list again @srbcheema1

**Comment by srbcheema1** [comment]
right now it is kept private. please contact @spider34 for access to the mailing list

**Comment by SouravSahoo** [comment]
Shut developed she seems to

**Comment by nimitbhardwaj** [comment]
@spider i will fail you in your project

**Comment by srbcheema1** [comment]
I have merged these changes into master. please update your master and from next time do make a pr from a branch other than master

**Comment by nimitbhardwaj** [comment]
I hate opensource.
May the father of understanding guide you

**Pull request merged**
